export type QualityBand = "elite" | "strong" | "mid" | "thin" | "unscored";

export type QualityScores = {
  recruitmentStrength: number | null;
  operationalMaturity: number | null;
  sponsorAttractiveness: number | null;
  therapeuticExpertise: number | null;
  overallSiteQuality: number | null;
  band: QualityBand;
};

export type Site = {
  id: string;
  name: string;
  website: string;
  hq: string;
  type: string;
  estimatedSiteCount: string;
  states: string;
  statesList: string[];
  icpScore: number;
  histTrials: number;
  completed: number;
  terminated: number;
  completionRate: number | null;
  activeNow: number;
  recruitingStudies?: number;
  phase2: number;
  phase3: number;
  totalEnrollment: number;
  firstStudyYear: number | null;
  yearsActive: number;
  therapeuticBreadth: number;
  performanceMatchConfidence: string;
  sponsorDiversity?: number | null;
  croDiversity?: number | null;
  repeatSponsors?: number | null;
  industrySponsoredStudies?: number | null;
  topSponsors?: string;
  namedCros?: string;
  publicationHistory?: number | null;
  ctms: string;
  ehr: string;
  eSource: boolean;
  eConsent: boolean;
  florence: boolean;
  crio: boolean;
  clinicalConductor: boolean;
  realTime: boolean;
  epic: boolean;
  cerner: boolean;
  therapeuticAreas: string;
  therapeuticSpecialties: string;
  languages: string;
  spanish: boolean;
  homeVisits: string;
  decentralizedCapabilities: string;
  mentionsDct: boolean;
  investigators: number | null;
  coordinators: number | null;
  sponsorsWorkedWith: string;
  crosWorkedWith: string;
  publicPartnerships: string;
  recentHiring: string;
  expansion: string;
  funding: string;
  acquisitions: string;
  ownerParent: string;
  facebookAds: boolean;
  metaPixel: boolean;
  googleAds: boolean;
  seo: string;
  trialFinder: boolean;
  patientDatabase: string;
  hasPatientDatabase: boolean;
  recruitmentPages: boolean;
  advertisesRecruitment: boolean;
  technologyStack: string;
  ctmsMentions: string;
  usesAi: boolean;
  buildsTech: string;
  currentRecruitingVisible: string;
  isRecruitingVisible: boolean;
  ceo: string;
  vpClinicalOps: string;
  vpSiteOps: string;
  vpRecruitment: string;
  contactEmails: string;
  linkedin: string;
  recruitmentCapability: string;
  notes: string;
  recruitSophistication: number;
  enrollmentVelocity: number;
  startupProxy: number;
  sponsorRichness: number;
  croRichness: number;
  scorable: boolean;
  scores: QualityScores;
};

export type SitesPayload = {
  meta: {
    generatedAt: string;
    source: string;
    scorecard: string;
    total: number;
    scored: number;
    unscored: number;
    scoresFromCsv?: number;
    note: string;
  };
  sites: Site[];
};

export type ProtocolDraft = {
  id: string;
  name: string;
  disease: string;
  indication: string;
  inclusion: string;
  exclusion: string;
  geography: string[];
  visitBurden: string;
  biomarkers: string;
  phase: string;
  enrollmentTarget: number;
  diversityGoals: string;
  requireSpanish: boolean;
  requireDct: boolean;
  rawText: string;
  restrictiveness: number;
};

export type RankedSite = {
  site: Site;
  rank: number;
  match: number;
  accrualIndex: number;
  indFit: number;
  enroll: number;
  ops: number;
  recruit: number;
  capacity: number;
  startup: number;
  diversity: number;
  geo: number;
  liftability: number;
  expectedWithIntera: number;
  reasons: string[];
  confidence: string;
};

export type RecommendationRun = {
  id: string;
  createdAt: string;
  protocol: ProtocolDraft;
  candidateCount: number;
  results: RankedSite[];
};
